export const flowers = [
  {
    name: "Rose Red",
    category: "Roses",
    stock: 1240,
    shelf: "6 days",
    expiry: "2 days",
    status: "Warning",
    cost: "Rp 6.500",
    season: "All year",
    rating: 4.9,
  },
  {
    name: "White Lily",
    category: "Lilies",
    stock: 840,
    shelf: "8 days",
    expiry: "5 days",
    status: "Healthy",
    cost: "Rp 8.200",
    season: "Spring",
    rating: 4.8,
  },
  {
    name: "Pink Peony",
    category: "Peonies",
    stock: 290,
    shelf: "5 days",
    expiry: "1 day",
    status: "Critical",
    cost: "Rp 15.500",
    season: "Spring",
    rating: 4.9,
  },
  {
    name: "Sunflower",
    category: "Seasonal",
    stock: 680,
    shelf: "7 days",
    expiry: "6 days",
    status: "Healthy",
    cost: "Rp 5.800",
    season: "Summer",
    rating: 4.7,
  },
  {
    name: "Purple Orchid",
    category: "Orchids",
    stock: 95,
    shelf: "12 days",
    expiry: "Expired",
    status: "Expired",
    cost: "Rp 18.000",
    season: "All year",
    rating: 4.8,
  },
];
export const trend = [
  { name: "Mon", sales: 18, stock: 82 },
  { name: "Tue", sales: 25, stock: 78 },
  { name: "Wed", sales: 21, stock: 75 },
  { name: "Thu", sales: 32, stock: 69 },
  { name: "Fri", sales: 39, stock: 64 },
  { name: "Sat", sales: 48, stock: 58 },
  { name: "Sun", sales: 44, stock: 56 },
];
export const branches = [
  {
    name: "Kemang",
    manager: "Dina Pratiwi",
    stock: "1,840 stems",
    status: "Healthy",
    city: "Jakarta Selatan",
  },
  {
    name: "Pondok Indah",
    manager: "Raka Putra",
    stock: "1,120 stems",
    status: "Warning",
    city: "Jakarta Selatan",
  },
  {
    name: "BSD",
    manager: "Alia Rahman",
    stock: "980 stems",
    status: "Healthy",
    city: "Tangerang Selatan",
  },
];
export const tasks = [
  {
    id: 1,
    title: "Rose Red · 500 stems",
    branch: "Kemang",
    status: "Requested",
  },
  { id: 2, title: "White Lily · 300 stems", branch: "BSD", status: "Approved" },
  {
    id: 3,
    title: "Sunflower · 240 stems",
    branch: "Pondok Indah",
    status: "Packing",
  },
  { id: 4, title: "Orchid · 100 stems", branch: "Kemang", status: "Shipping" },
  { id: 5, title: "Peony · 150 stems", branch: "BSD", status: "Delivered" },
];
